[EventStream]
type = "LogstreamerInput"
log_directory = "/data"
file_match = '(?P<FileName>[^/]+).log'
differentiator = ["FileName", "-logs"]

[PayloadEncoder]
append_newlines = false

[EventStreamLocalCopy]
type = "FileOutput"
message_matcher = "TRUE"
path = "/var/log/heka/dump.log"
perm = "666"
flush_count = 100
flush_operator = "OR"
encoder = "PayloadEncoder"
