[EventStream]
type = "LogstreamerInput"
log_directory = "%ENV[DATA_DIR]"
file_match = '%ENV[FILE_MATCH]'
differentiator = ["FileName", "-logs"]

[PayloadEncoder]
append_newlines = false

[KafkaOutput]
type = "KafkaOutput"
message_matcher = "TRUE"
topic = "%ENV[KAFKA_TOPIC]"
addrs = ["%ENV[KAFKA_ADDR]"]
required_acks = "%ENV[KAFKA_ACK]"
id = "%ENV[KAFKA_CLIENT_ID]"
encoder = "PayloadEncoder"

[hekad]
base_dir = "/usr/local/heka/db"
maxprocs = %ENV[HEKA_MAXPROCS]
