[EventStream]
type = "LogstreamerInput"
log_directory = "/data"
file_match = 'events\.log'

[PayloadEncoder]
append_newlines = false

[KafkaOutput]
type = "KafkaOutput"
message_matcher = "TRUE"
topic = "heka_test1"
addrs = ["%ENV[KAFKA_IP_ADDR]:9092"]
required_acks = "WaitForAll"
id = "heka_client1"
encoder = "PayloadEncoder"

[hekad]
base_dir = "/usr/local/heka/db"
